# -*- coding: utf-8 -*-
"""
This module implements unit tests testcase.py.

"""

import os
import unittest
import numpy as np
import pandas as pd
import testcase
import utilities

testing_root_dir = os.path.join(utilities.get_root_path(), 'testing')

reference_result_directory = 'testcase'

class partialAdvance(utilities.partialChecks):
    '''Tests for the testcase.TestCase.advance API.

    The reference is generated by the default simulation path, so running
    these against the fast path checks that the two agree.

    '''

    def test_check_input_for_zero(self):
        '''Test that an overwrite value of 0 given in float is used.

        '''

        self.testcase.set_step(60)
        # Advance first wih fan speed of 0.5, then with fan speed of 0.0.
        u = {'fcu_oveFan_u': 0.5,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        u = {'fcu_oveFan_u': 0.0,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        # Get results
        status, message, payload = self.testcase.get_results(['fcu_reaPFan_y', 'fcu_oveFan_u'],
                                                             0,
                                                             payload['time'])
        # Test results
        df = pd.DataFrame(payload).set_index('time')
        ref_filepath = os.path.join(testing_root_dir, 'references', reference_result_directory, 'check_input_for_zero.csv')
        self.compare_ref_timeseries_df(df, ref_filepath)

class Advance(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API on the default
    simulation path.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.assertFalse(self.testcase.fast,
                         'The low-overhead simulation path must be off unless asked for.')

class AdvanceFast(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API on the low-overhead
    simulation path.

    Runs the same checks against the same references as ``Advance``.  The
    references were generated on the default path, so agreeing with them is
    what says the two paths simulate the same thing.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air with fast=True.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu',
                                 fast=True)
        self.assertTrue(self.testcase.fast)

class FastOption(unittest.TestCase):
    '''Unit tests for how the low-overhead simulation path is switched on.

    '''

    def test_default_is_off(self):
        '''Test that the path is off unless it is asked for.

        '''

        self.assertFalse(self._make().fast)

    def test_argument_enables_it(self):
        '''Test that the argument switches the path on.

        '''

        self.assertTrue(self._make(fast=True).fast)

    def _make(self, **kwargs):
        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        return TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu', **kwargs)


class GetKpis(unittest.TestCase, utilities.partialChecks):
    '''Unit tests for the testcase.TestCase.get_kpis API.

    '''

    def test_all_kpis_by_default(self):
        '''Test that omitting names returns every core KPI, as before.

        '''

        status, message, payload = self.testcase.get_kpis()
        self.assertEqual(status, 200)
        self.assertEqual(list(payload.keys()),
                         self.testcase.cal.get_core_kpi_names())

    def test_subset_of_kpis(self):
        '''Test that naming KPIs returns those and only those, with the same
        values a request for all of them gives.

        '''

        names = ['cost_tot', 'tdis_tot']
        status, message, payload_all = self.testcase.get_kpis()
        self.assertEqual(status, 200)
        status, message, payload_sub = self.testcase.get_kpis(names)
        self.assertEqual(status, 200)
        self.assertEqual(sorted(payload_sub.keys()), sorted(names))
        for name in names:
            self.assertEqual(payload_sub[name], payload_all[name],
                             '{0} differs when requested on its own.'.format(name))

    def test_single_kpi_as_string(self):
        '''Test that a single name may be given as a string.

        '''

        status, message, payload = self.testcase.get_kpis('cost_tot')
        self.assertEqual(status, 200)
        self.assertEqual(list(payload.keys()), ['cost_tot'])

    def test_invalid_kpi_name(self):
        '''Test that an unknown KPI name is reported as a bad request rather
        than silently ignored or raised as an internal error.

        '''

        status, message, payload = self.testcase.get_kpis(['cost_tot', 'not_a_kpi'])
        self.assertEqual(status, 400)
        self.assertIsNone(payload)
        self.assertTrue('not_a_kpi' in message)

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.testcase.initialize(0, 0)
        self.testcase.set_step(3600)
        self.testcase.advance(u={})

class WarmupInterval(unittest.TestCase, utilities.partialChecks):
    '''Unit tests for the warmup simulation grid option of initialize.

    '''

    def test_default_is_thirty(self):
        '''Test that the warmup grid is 30 s unless asked otherwise, which is
        the behaviour of earlier BOPTEST versions.

        '''

        self.testcase.initialize(24*3600, 3600)
        times = np.array(self.testcase.y_store['time'])
        warmup = times[times <= 24*3600]
        np.testing.assert_array_equal(np.unique(np.diff(warmup)), [30])

    def test_rejects_non_positive(self):
        '''Test that a grid of zero or less is refused rather than producing a
        division by zero deep in the simulation.

        '''

        for value in [0, -30]:
            with self.assertRaises(ValueError):
                self.testcase.initialize(24*3600, 3600, warmup_interval=value)

    def test_only_the_warmup_grid_changes(self):
        '''Test that the option coarsens the warmup period only, and leaves
        the test period on the mandated 30 s grid that the KPIs integrate
        over.

        '''

        start_time, warmup_period, step, nsteps = 24*3600, 3600, 900, 4
        for warmup_interval in [30, 900]:
            self.testcase.initialize(start_time, warmup_period,
                                     warmup_interval=warmup_interval)
            self.testcase.set_step(step)
            for _ in range(nsteps):
                self.testcase.advance(u={})

            times = np.array(self.testcase.y_store['time'])
            warmup_times = times[times <= start_time]
            test_times = times[times >= start_time]

            np.testing.assert_array_equal(
                np.unique(np.diff(warmup_times)), [warmup_interval],
                'The warmup period should be recorded on the requested grid.')
            np.testing.assert_array_equal(
                np.unique(np.diff(test_times)), [30],
                'The test period must stay on the 30 s grid whatever the '
                'warmup grid is.')
            self.assertEqual(test_times[0], start_time)
            self.assertEqual(test_times[-1], start_time + nsteps*step)

    def test_kpi_integration_still_starts_at_the_start_time(self):
        '''Test that the KPI calculator excludes the warmup samples whatever
        grid they were recorded on.  It selects them by time rather than by
        counting samples, so a coarser warmup grid must not shift the point
        the integration begins at.

        '''

        start_time, warmup_period = 24*3600, 3600
        for warmup_interval in [30, 900]:
            self.testcase.initialize(start_time, warmup_period,
                                     warmup_interval=warmup_interval)
            self.testcase.cal.initialize()
            i = self.testcase.cal.i_last_tdis
            self.assertTrue(self.testcase.y_store['time'][i] >= start_time)
            self.assertTrue(self.testcase.y_store['time'][i-1] < start_time)

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')


if __name__ == '__main__':
    utilities.run_tests(os.path.basename(__file__))
