# -*- coding: utf-8 -*-
"""
This module implements unit tests testcase.py.

"""

import os
import unittest
import pandas as pd
import testcase
import utilities

testing_root_dir = os.path.join(utilities.get_root_path(), 'testing')

reference_result_directory = 'testcase'

class partialAdvance(utilities.partialChecks):
    '''Tests for the testcase.TestCase.advance API.

    The reference is generated by the default simulation path, so running
    these against the fast path checks that the two agree.

    '''

    def test_check_input_for_zero(self):
        '''Test that an overwrite value of 0 given in float is used.

        '''

        self.testcase.set_step(60)
        # Advance first wih fan speed of 0.5, then with fan speed of 0.0.
        u = {'fcu_oveFan_u': 0.5,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        u = {'fcu_oveFan_u': 0.0,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        # Get results
        status, message, payload = self.testcase.get_results(['fcu_reaPFan_y', 'fcu_oveFan_u'],
                                                             0,
                                                             payload['time'])
        # Test results
        df = pd.DataFrame(payload).set_index('time')
        ref_filepath = os.path.join(testing_root_dir, 'references', reference_result_directory, 'check_input_for_zero.csv')
        self.compare_ref_timeseries_df(df, ref_filepath)

class Advance(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API on the default
    simulation path.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.assertFalse(self.testcase.fast,
                         'The low-overhead simulation path must be off unless asked for.')

class AdvanceFast(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API on the low-overhead
    simulation path.

    Runs the same checks against the same references as ``Advance``.  The
    references were generated on the default path, so agreeing with them is
    what says the two paths simulate the same thing.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air with fast=True.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu',
                                 fast=True)
        self.assertTrue(self.testcase.fast)

class FastOption(unittest.TestCase):
    '''Unit tests for how the low-overhead simulation path is switched on.

    '''

    def test_default_is_off(self):
        '''Test that the path is off when neither the argument nor the
        environment variable asks for it.

        '''

        self.assertFalse(self._make().fast)

    def test_environment_variable(self):
        '''Test that BOPTEST_FAST turns the path on, and that anything other
        than an affirmative value leaves it off.

        '''

        for value in ['1', 'true', 'True', 'yes', 'on', ' TRUE ']:
            os.environ['BOPTEST_FAST'] = value
            self.assertTrue(self._make().fast,
                            'BOPTEST_FAST={0} should enable the path.'.format(value))
        for value in ['', '0', 'false', 'no', 'off']:
            os.environ['BOPTEST_FAST'] = value
            self.assertFalse(self._make().fast,
                             'BOPTEST_FAST={0} should not enable the path.'.format(value))

    def test_argument_beats_environment_variable(self):
        '''Test that an explicit argument wins over the environment variable.

        '''

        os.environ['BOPTEST_FAST'] = 'true'
        self.assertFalse(self._make(fast=False).fast)
        os.environ['BOPTEST_FAST'] = 'false'
        self.assertTrue(self._make(fast=True).fast)

    def _make(self, **kwargs):
        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        return TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu', **kwargs)

    def tearDown(self):
        os.environ.pop('BOPTEST_FAST', None)

if __name__ == '__main__':
    utilities.run_tests(os.path.basename(__file__))
