# -*- coding: utf-8 -*-
"""
This module implements unit tests testcase.py.

"""

import os
import logging
import unittest
import numpy as np
import pandas as pd
import testcase
import utilities

testing_root_dir = os.path.join(utilities.get_root_path(), 'testing')

reference_result_directory = 'testcase'

class partialAdvance(utilities.partialChecks):
    '''Tests for the testcase.TestCase.advance API.

    The reference is generated by calling fmu.simulate, so running these with
    direct stepping checks that the two agree.

    '''

    def test_check_input_for_zero(self):
        '''Test that an overwrite value of 0 given in float is used.

        '''

        self.testcase.set_step(60)
        # Advance first wih fan speed of 0.5, then with fan speed of 0.0.
        u = {'fcu_oveFan_u': 0.5,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        u = {'fcu_oveFan_u': 0.0,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        # Get results
        status, message, payload = self.testcase.get_results(['fcu_reaPFan_y', 'fcu_oveFan_u'],
                                                             0,
                                                             payload['time'])
        # Test results
        df = pd.DataFrame(payload).set_index('time')
        ref_filepath = os.path.join(testing_root_dir, 'references', reference_result_directory, 'check_input_for_zero.csv')
        self.compare_ref_timeseries_df(df, ref_filepath)

class Advance(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API through fmu.simulate.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.assertFalse(self.testcase.direct_step,
                         'Direct stepping must be off unless asked for.')

class AdvanceDirectStep(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API with direct stepping.

    Runs the same checks against the same references as ``Advance``, which were
    generated through fmu.simulate, so agreeing with them is what says the two
    simulate the same thing.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air with direct_step=True.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu',
                                 direct_step=True)
        self.assertTrue(self.testcase.direct_step)

class DirectStepOption(unittest.TestCase):
    '''Unit tests for how direct stepping is switched on.

    '''

    def test_default_is_off(self):
        '''Test that direct stepping is off unless it is asked for.

        '''

        self.assertFalse(self._make().direct_step)

    def test_argument_enables_it(self):
        '''Test that the argument switches direct stepping on.

        '''

        self.assertTrue(self._make(direct_step=True).direct_step)

    def _make(self, **kwargs):
        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        return TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu', **kwargs)


class GetKpis(unittest.TestCase, utilities.partialChecks):
    '''Unit tests for the testcase.TestCase.get_kpis API.

    '''

    def test_all_kpis_by_default(self):
        '''Test that omitting names returns every core KPI, as before.

        '''

        status, message, payload = self.testcase.get_kpis()
        self.assertEqual(status, 200)
        self.assertEqual(list(payload.keys()),
                         self.testcase.cal.get_core_kpi_names())

    def test_subset_of_kpis(self):
        '''Test that naming KPIs returns those and only those, with the same
        values a request for all of them gives.

        '''

        names = ['cost_tot', 'tdis_tot']
        status, message, payload_all = self.testcase.get_kpis()
        self.assertEqual(status, 200)
        status, message, payload_sub = self.testcase.get_kpis(names)
        self.assertEqual(status, 200)
        self.assertEqual(sorted(payload_sub.keys()), sorted(names))
        for name in names:
            self.assertEqual(payload_sub[name], payload_all[name],
                             '{0} differs when requested on its own.'.format(name))

    def test_single_kpi_as_string(self):
        '''Test that a single name may be given as a string.

        '''

        status, message, payload = self.testcase.get_kpis('cost_tot')
        self.assertEqual(status, 200)
        self.assertEqual(list(payload.keys()), ['cost_tot'])

    def test_invalid_kpi_name(self):
        '''Test that an unknown KPI name is reported as a bad request rather
        than silently ignored or raised as an internal error.

        '''

        status, message, payload = self.testcase.get_kpis(['cost_tot', 'not_a_kpi'])
        self.assertEqual(status, 400)
        self.assertIsNone(payload)
        self.assertTrue('not_a_kpi' in message)

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.testcase.initialize(0, 0)
        self.testcase.set_step(3600)
        self.testcase.advance(u={})
class LogLevels(unittest.TestCase):
    '''Unit tests for the log level arguments of testcase.TestCase.

    '''

    def test_defaults_are_unchanged(self):
        '''Test that the defaults are the levels earlier versions hard-coded.

        '''

        case = self._make()
        self.assertEqual(case.fmu.get_log_level(), 7)
        self.assertEqual(logging.getLogger().level, logging.DEBUG)

    def test_levels_are_applied(self):
        '''Test that both levels are set to what was asked for.

        '''

        case = self._make(fmu_log_level=0, log_level=logging.WARNING)
        self.assertEqual(case.fmu.get_log_level(), 0)
        self.assertEqual(logging.getLogger().level, logging.WARNING)

    def _make(self, **kwargs):
        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        return TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu', **kwargs)


class WarmupInterval(unittest.TestCase, utilities.partialChecks):
    '''Unit tests for the warmup_interval argument of testcase.TestCase.initialize.

    '''

    def test_warmup_grid(self):
        '''Test that the warmup period uses the requested grid, that omitting
        the argument keeps 30 s, and that the test period stays on 30 s.

        '''

        start_time, warmup_period, step, nsteps = 24*3600, 3600, 900, 4
        for warmup_interval, expected in [(None, 30), (30, 30), (900, 900)]:
            kwargs = {} if warmup_interval is None else \
                {'warmup_interval': warmup_interval}
            self.testcase.initialize(start_time, warmup_period, **kwargs)
            self.testcase.set_step(step)
            for _ in range(nsteps):
                self.testcase.advance(u={})
            # Split the stored trajectory at the start time
            times = np.array(self.testcase.y_store['time'])
            warmup_times = times[times <= start_time]
            test_times = times[times >= start_time]
            np.testing.assert_array_equal(np.unique(np.diff(warmup_times)),
                                          [expected])
            np.testing.assert_array_equal(np.unique(np.diff(test_times)), [30])
            self.assertEqual(test_times[-1], start_time + nsteps*step)

    def test_rejects_invalid(self):
        '''Test that a grid that is not a positive number gives a 400.

        '''

        for value in [0, -30, 'abc']:
            status, message, payload = \
                self.testcase.initialize(24*3600, 3600, warmup_interval=value)
            self.assertEqual(status, 400)
            self.assertEqual(payload, None)
            self.assertTrue('warmup_interval' in message)

    def test_kpi_integration_starts_at_the_start_time(self):
        '''Test that the warmup samples are excluded from the KPI integration
        whatever grid they were recorded on.

        '''

        start_time, warmup_period = 24*3600, 3600
        for warmup_interval in [30, 900]:
            self.testcase.initialize(start_time, warmup_period,
                                     warmup_interval=warmup_interval)
            self.testcase.cal.initialize()
            i = self.testcase.cal.i_last_tdis
            self.assertTrue(self.testcase.y_store['time'][i] >= start_time)
            self.assertTrue(self.testcase.y_store['time'][i-1] < start_time)

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')


if __name__ == '__main__':
    utilities.run_tests(os.path.basename(__file__))
